services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    privileged: true
    ports:
      - "9000:9000"     # Porta HTTP
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /:/host:ro
      - portainer_data:/data

volumes:
  portainer_data:
    driver: local
