services:
  portainer:
    image: portainer/portainer-ce:2.21.5
    container_name: portainer
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    restart: always

volumes:
  portainer_data:
    driver: local
